name: wuchuheng_local_cache
description: This is a local cache libery.
version: 0.0.2
homepage: https://github.com/wuchuheng/local_cache_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path_provider: ^2.0.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
